// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

// Enhanced error checking and debugging
if (!SUPABASE_URL) {
  console.error("❌ VITE_SUPABASE_URL is not set. Please check your environment variables.");
  console.error("Current environment variables:", import.meta.env);
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error("❌ VITE_SUPABASE_ANON_KEY is not set. Please check your environment variables.");
  console.error("Current environment variables:", import.meta.env);
}

// Additional validation
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("❌ Supabase client will not be properly initialized. This will cause runtime errors.");
  // In production, you might want to throw an error to prevent the app from running
  if (import.meta.env.PROD) {
    throw new Error("Supabase configuration is missing. Please check your environment variables.");
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);