// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uprwkbytxbkzpvupsnme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwcndrYnl0eGJrenB2dXBzbm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MDk1MDcsImV4cCI6MjA2NDk4NTUwN30.PJN0mba_wLqjXFAwPDgWGwGJ5LGuTOX_j4OPv1dJK9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);